<?
$gennasten= array(
	'/collections/nastennaya-plitka-cenoj-do-700-rublej',
	'/collections/nastennaya-plitka-do-1000-rubley',
	'/collections/nastennaya-plitka-do-1500-rubley',
	'/collections/nastennaya-plitka-do-2000-rubley',
	'/collections/nastennaya-plitka-svyshe-2000-rubley',
	'/collections/bezhevaya-nastennaya-plitka',
	'/collections/belaya-nastennaya-plitka',
	'/collections/golubaya-nastennaya-plitka',
	'/collections/zheltaya-nastennaya-plitka',
	'/collections/zelenaya-nastennaya-plitka',
	'/collections/krasnaya-nastennaya-plitka',
	'/collections/multikolor-nastennaya-plitka',
	'/collections/oranzhevaya-nastennaya-plitka',
	'/collections/rozovaya-nastennaya-plitka',
	'/collections/seraya-nastennaya-plitka',
	'/collections/sinyaya-nastennaya-plitka',
	'/collections/fioletovaya-nastennaya-plitka',
	'/collections/korichnevaya-nastennaya-plitka',
	'/collections/chernaya-nastennaya-plitka',
	'/collections/cherno-belaya-nastennaya-plitka',
	'/collections/nastennaya-plitka-10x10',
	'/collections/nastennaya-plitka-15x15',
	'/collections/nastennaya-plitka-20x20',
	'/collections/nastennaya-plitka-30x30',
	'/collections/nastennaya-plitka-40x40',
	'/collections/nastennaya-plitka-30x60',
	'/collections/nastennaya-plitka-50x50',
	'/collections/nastennaya-plitka-60x60',
	'/collections/nastennaya-plitka-80x80',
	'/collections/avstraliyskaya-nastennaya-plitka',
	'/collections/angliyskaya-nastennaya-plitka',
	'/collections/belorusskaya-nastennaya-plitka',
	'/collections/bolgarskaya-nastennaya-plitka',
	'/collections/vetnamskaya-nastennaya-plitka',
	'/collections/germanskaya-nastennaya-plitka',
	'/collections/egipetskaya-nastennaya-plitka',
	'/collections/indiyskaya-nastennaya-plitka',
	'/collections/ispanskaya-nastennaya-plitka',
	'/collections/italyanskaya-nastennaya-plitka',
	'/collections/kitayskaya-nastennaya-plitka',
	'/collections/litovskaya-nastennaya-plitka',
	'/collections/moldavskaya-nastennaya-plitka',
	'/collections/polskaya-nastennaya-plitka',
	'/collections/portugalskaya-nastennaya-plitka',
	'/collections/rossiyskaya-nastennaya-plitka',
	'/collections/tayvanskaya-nastennaya-plitka',
	'/collections/tunisskaya-nastennaya-plitka',
	'/collections/turetskaya-nastennaya-plitka',
	'/collections/ukrainskaya-nastennaya-plitka',
	'/collections/khorvatskaya-nastennaya-plitka',
	'/collections/cheshskaya-nastennaya-plitka',
	'/collections/yuzhno-koreyskaya-nastennaya-plitka',
	'/collections/glyantsevaya-nastennaya-plitka',
	'/collections/matovaya-nastennaya-plitka',
	'/collections/relefnaya-nastennaya-plitka',	
);

if (in_array($_SERVER['SCRIPT_URL'], $gennasten)) {
	define("PAGE_BOTTOM_TEXT", "<p>".PAGE_TITLE." — идеальный выбор для тех, кто одинаково ценит практичность и эстетичность. В этом настенном кафеле удивительным образом сочетаются продуманный дизайн, в котором прослеживается влияние современных модных трендов, и превосходные эксплуатационные характеристики: </p>
	<ul>
		<li>стойкость к износу (поверхность сохраняет целостность и презентабельный вид даже при сильных механических нагрузках);</li>
		<li>индифферентность к повышенной влажности, температурным скачкам, ультрафиолетовому излучению и другим агрессивным факторам среды (такая стойкость существенно расширяет сферу использования материала);</li>
		<li>неприхотливость в уходе (поддержание идеального вида не требует сложных манипуляций и специализированных очищающих средств).</li>
	</ul>
	<p>".PAGE_TITLE." — качественный облицовочный материал, созданный по актуальным отраслевым стандартам из экологически безопасного сырья, прошедшего многоступенчатую обработку. Отсюда и отличные прочностные характеристики, и стабильная геометрия, не меняющаяся со временем.</p>");
	// $sotbitSeoMetaBottomDesc=;
}

$genvanna= array(
	'/collections/bezhevaya-plitka-dlya-vannoy',
	'/collections/belaya-plitka-dlya-vannoy',
	'/collections/zheltaya-plitka-dlya-vannoy',
	'/collections/zelenaya-plitka-dlya-vannoy',
	'/collections/korichnevaya-plitka-dlya-vannoy',
	'/collections/krasnaya-plitka-dlya-vannoy',
	'/collections/multikolor-plitka-dlya-vannoy',
	'/collections/oranzhevaya-plitka-dlya-vannoy',
	'/collections/rozovaya-plitka-dlya-vannoy',
	'/collections/seraya-plitka-dlya-vannoy',
	'/collections/sinyaya-plitka-dlya-vannoy',
	'/collections/chernaya-plitka-dlya-vannoy',
	'/collections/avstraliyskaya-plitka-dlya-vannoy',
	'/collections/angliyskaya-plitka-dlya-vannoy',
	'/collections/bolgarskaya-plitka-dlya-vannoy',
	'/collections/vetnamskaya-plitka-dlya-vannoy',
	'/collections/germanskaya-plitka-dlya-vannoy',
	'/collections/egipetskaya-plitka-dlya-vannoy',
	'/collections/indiyskaya-plitka-dlya-vannoy',
	//'/collections/ispanskaya-plitka-dlya-vannoy',
	'/collections/italyanskaya-plitka-dlya-vannoy',
	'/collections/kitayskaya-plitka-dlya-vannoy',
	'/collections/litovskaya-plitka-dlya-vannoy',
	'/collections/moldavskaya-plitka-dlya-vannoy',
	'/collections/polskaya-plitka-dlya-vannoy',
	'/collections/portugalskaya-plitka-dlya-vannoy',
	'/collections/rossiyskaya-plitka-dlya-vannoy',
	'/collections/tayvanskaya-plitka-dlya-vannoy',
	'/collections/tunisskaya-plitka-dlya-vannoy',
	'/collections/turetskaya-plitka-dlya-vannoy',
	'/collections/ukrainskaya-plitka-dlya-vannoy',
	'/collections/khorvatskaya-plitka-dlya-vannoy',
	'/collections/cheshskaya-plitka-dlya-vannoy',
	'/collections/yuzhno-koreyskaya-plitka-dlya-vannoy',
	'/collections/plitka-dlya-vannoy-10x10',
	'/collections/plitka-dlya-vannoy-15x15',
	'/collections/plitka-dlya-vannoy-20x20',
	'/collections/plitka-dlya-vannoy-30x30',
	'/collections/plitka-dlya-vannoy-40x40',
	'/collections/plitka-dlya-vannoy-50x50',
	'/collections/plitka-dlya-vannoy-60x60',
	'/collections/plitka-dlya-vannoy-80x80',
	'/collections/plitka-dlya-vannoy-30x60',
	'/collections/matovaya-plitka-dlya-vannoy',
	'/collections/glyantsevaya-plitka-dlya-vannoy',
	'/collections/relefnaya-plitka-dlya-vannoy',
	'/collections/plitka-dlya-vannoy-do-700-rubley',
	'/collections/plitka-dlya-vannoy-do-1000-rubley',
	'/collections/plitka-dlya-vannoy-do-1500-rubley',
	'/collections/plitka-dlya-vannoy-do-2000-rubley',
	'/collections/plitka-dlya-vannoy-svyshe-2000-rubley',	
	);

if (in_array($_SERVER['SCRIPT_URL'], $genvanna)) {
	define("PAGE_BOTTOM_TEXT", "<p>Современные облицовочные материалы поражают разнообразием: можно найти идеальный материал для любого стиля и на любой бюджет. Дизайнеры фабрик ищут вдохновение в разных сферах и создают уникальные коллекции изделий с неповторимым декором и прекрасными эксплуатационными характеристиками. ".PAGE_TITLE." — яркий образец керамики с оптимальным соотношением стоимости и качества. Продукция хорошо переносит воздействие влаги, как и положено кафелю для ванной, сохраняет форму и целостность поверхности даже при постоянных сменах температурного режима, легко очищается от загрязнений.</p>
<p>Для производства облицовки используется отборное сырье, а его многоступенчатая обработка позволяет повысить прочностные свойства конечной продукции, что гарантирует длительный срок службы в любых условиях эксплуатации. ".PAGE_TITLE." из нашего каталога — это еще и эталон эстетичности. Плитка прекрасно смотрится в разных интерьерных стилях и хорошо сочетается с другими материалами.</p>");
}

$genkukh= array(
	'/collections/bezhevaya-plitka-dlya-kukhni',
	'/collections/belaya-plitka-dlya-kukhni',
	'/collections/golubaya-plitka-dlya-kukhni',
	'/collections/zheltaya-plitka-dlya-kukhni',
	'/collections/zelenaya-plitka-dlya-kukhni',
	'/collections/korichnevaya-plitka-dlya-kukhni',
	'/collections/krasnaya-plitka-dlya-kukhni',
	'/collections/multikolor-plitka-dlya-kukhni',
	'/collections/oranzhevaya-plitka-dlya-kukhni',
	'/collections/rozovaya-plitka-dlya-kukhni',
	'/collections/seraya-plitka-dlya-kukhni',
	'/collections/sinyaya-plitka-dlya-kukhni',
	'/collections/fioletovaya-plitka-dlya-kukhni',
	'/collections/cherno-belaya-plitka-dlya-kukhni',
	'/collections/chernaya-plitka-dlya-kukhni',
	'/collections/plitka-dlya-kukhni-do-1000-rubley',
	'/collections/plitka-dlya-kukhni-do-1500-rubley',
	'/collections/plitka-dlya-kukhni-do-2000-rubley',
	'/collections/plitka-dlya-kukhni-svyshe-2000-rubley',
	'/collections/plitka-dlya-kukhni-10x10',
	'/collections/plitka-dlya-kukhni-15x15',
	'/collections/plitka-dlya-kukhni-20x20',
	'/collections/plitka-dlya-kukhni-30x30',
	'/collections/plitka-dlya-kukhni-40x40',
	'/collections/plitka-dlya-kukhni-30x60',
	'/collections/plitka-dlya-kukhni-50x50',
	'/collections/plitka-dlya-kukhni-60x60',
	'/collections/plitka-dlya-kukhni-80x80',
	'/collections/glyantsevaya-plitka-dlya-kukhni',
	'/collections/matovaya-plitka-dlya-kukhni',
	'/collections/relefnaya-plitka-dlya-kukhni',
	'/collections/avstraliyskaya-plitka-dlya-kukhni',
	'/collections/angliyskaya-plitka-dlya-kukhni',
	'/collections/belorusskaya-plitka-dlya-kukhni',
	'/collections/bolgarskaya-plitka-dlya-kukhni',
	'/collections/vetnamskaya-plitka-dlya-kukhni',
	'/collections/germanskaya-plitka-dlya-kukhni',
	'/collections/egipetskaya-plitka-dlya-kukhni',
	'/collections/indiyskaya-plitka-dlya-kukhni',
	'/collections/ispanskaya-plitka-dlya-kukhni',
	'/collections/italyanskaya-plitka-dlya-kukhni',
	'/collections/kitayskaya-plitka-dlya-kukhni',
	'/collections/litovskaya-plitka-dlya-kukhni',
	'/collections/moldavskaya-plitka-dlya-kukhni',
	'/collections/polskaya-plitka-dlya-kukhni',
	'/collections/portugalskaya-plitka-dlya-kukhni',
	'/collections/rossiyskaya-plitka-dlya-kukhni',
	'/collections/tayvanskaya-plitka-dlya-kukhni',
	'/collections/tunisskaya-plitka-dlya-kukhni',
	'/collections/turetskaya-plitka-dlya-kukhni',
	'/collections/ukrainskaya-plitka-dlya-kukhni',
	'/collections/khorvatskaya-plitka-dlya-kukhni',
	'/collections/cheshskaya-plitka-dlya-kukhni',
	'/collections/yuzhno-koreyskaya-plitka-dlya-kukhni',
	'/collections/plitka-na-fartuk',
	);

if (in_array($_SERVER['SCRIPT_URL'], $genkukh)) {
	define("PAGE_BOTTOM_TEXT", "<p>Каким должен быть идеальный кафель для кухни? Прежде всего, прочным, способным выдерживать механические нагрузки, в числе которых ударные. Во-вторых, влагостойким, ведь конденсата и брызг в кухонном помещении не избежать. И, конечно, стильным, гармонично вписывающимся в основную дизайнерскую концепцию интерьера. ".PAGE_TITLE." — эталонная продукция по всем указанным критериям.</p>
<p>Представленные облицовочные материалы способны долгое время выдерживать интенсивную эксплуатацию без видимых следов износа. Они неприхотливы в уходе: за счет особой структуры не впитывают грязь, поэтому с поддержанием презентабельного вида поверхности проблем не будет. Керамика сохраняет первоначальный цвет даже под прямыми солнечными лучами и хорошо справляется со сменой температурно-влажностного режима. ".PAGE_TITLE." — рациональный выбор, если вы хотите получить долговечную и эстетичную отделку.</p>");
}

$genpol= array(
	'/collections/bezhevaya-napolnaya-plitka',
	'/collections/belaya-napolnaya-plitka',
	'/collections/golubaya-napolnaya-plitka',
	'/collections/zheltaya-napolnaya-plitka',
	'/collections/zelenaya-napolnaya-plitka',
	'/collections/korichnevaya-napolnaya-plitka',
	'/collections/krasnaya-napolnaya-plitka',
	'/collections/multikolor-napolnaya-plitka',
	'/collections/oranzhevaya-napolnaya-plitka',
	'/collections/rozovaya-napolnaya-plitka',
	'/collections/seraya-napolnaya-plitka',
	'/collections/sinyaya-napolnaya-plitka',
	'/collections/fioletovaya-napolnaya-plitka',
	'/collections/chernaya-napolnaya-plitka',
	'/collections/napolnaya-plitka-10x10',
	'/collections/napolnaya-plitka-20x20',
	'/collections/napolnaya-plitka-30x30',
	'/collections/napolnaya-plitka-40x40',
	'/collections/napolnaya-plitka-50x50',
	'/collections/napolnaya-plitka-60x60',
	'/collections/napolnaya-plitka-80x80',
	'/collections/napolnaya-plitka-30x60',
	'/collections/glyantsevaya-napolnaya-plitka',
	'/collections/matovaya-napolnaya-plitka',
	'/collections/relefnaya-napolnaya-plitka',
	'/collections/napolnaya-plitka-do-700-rubley',
	'/collections/napolnaya-plitka-do-1000-rubley',
	'/collections/napolnaya-plitka-do-1500-rubley',
	'/collections/napolnaya-plitka-do-2000-rubley',
	'/collections/napolnaya-plitka-svyshe-2000-rubley',
	'/collections/avstraliyskaya-napolnaya-plitka',
	'/collections/angliyskaya-napolnaya-plitka',
	'/collections/belorusskaya-napolnaya-plitka',
	'/collections/bolgarskaya-napolnaya-plitka',
	'/collections/vetnamskaya-napolnaya-plitka',
	'/collections/germanskaya-napolnaya-plitka',
	'/collections/egipetskaya-napolnaya-plitka',
	'/collections/indiyskaya-napolnaya-plitka',
	'/collections/italyanskaya-napolnaya-plitka',
	'/collections/kitayskaya-napolnaya-plitka',
	'/collections/litovskaya-napolnaya-plitka',
	'/collections/moldavskaya-napolnaya-plitka',
	'/collections/polskaya-napolnaya-plitka',
	'/collections/portugalskaya-napolnaya-plitka',
	'/collections/rossiyskaya-napolnaya-plitka',
	'/collections/tayvanskaya-napolnaya-plitka',
	'/collections/tunisskaya-napolnaya-plitka',
	'/collections/turetskaya-napolnaya-plitka',
	'/collections/ukrainskaya-napolnaya-plitka',
	'/collections/khorvatskaya-napolnaya-plitka',
	'/collections/cheshskaya-napolnaya-plitka',
	'/collections/yuzhno-koreyskaya-napolnaya-plitka',
	);

if (in_array($_SERVER['SCRIPT_URL'], $genpol)) {
	define("PAGE_BOTTOM_TEXT", "<p>На пол приходится самая большая нагрузка в любом помещении, поэтому к выбору отделочного материала в данном случае стоит подходить очень внимательно. Напольная плитка должна отвечать строгим требованиям в плане прочности, влаго- и износостойкости, невосприимчивости к налету и грибку. Важную роль, конечно, играет и дизайн, ведь материал должен стать частью общей стилевой концепции. ".PAGE_TITLE." из нашего каталога — это эталонная продукция, созданная по строгим стандартам качества. Она имеет высокие показатели по всем указанным параметрам и укладывается в помещениях разного типа.</p>
<p>Керамика стильно выглядит, демонстрирует высокую стойкость к агрессии среды и легко справляется с интенсивной эксплуатацией, сохраняя презентабельный вид на протяжении всего срока службы, который исчисляется десятками лет. Благодаря особенностям использованного сырья покрытие не впитывает грязь, поэтому легко чистится. ".PAGE_TITLE." — идеальный выбор и по такому критерию, как экологичность.</p>");
}

$genmoz= array(
	'/collections/bezhevaya-mozaika',
	'/collections/belaya-mozaika',
	'/collections/golubaya-mozaika',
	'/collections/zheltaya-mozaika',
	'/collections/zelenaya-mozaika',
	'/collections/korichnevaya-mozaika',
	'/collections/krasnaya-mozaika',
	'/collections/multikolor-mozaika',
	'/collections/oranzhevaya-mozaika',
	'/collections/rozovaya-mozaika',
	'/collections/seraya-mozaika',
	'/collections/sinyaya-mozaika',
	'/collections/fioletovaya-mozaika',
	'/collections/cherno-belaya-mozaika',
	'/collections/chernaya-mozaika',
	'/collections/mozaika-do-700-rubley',
	'/collections/mozaika-do-1000-rubley',
	'/collections/mozaika-do-1500-rubley',
	'/collections/mozaika-svyshe-2000-rubley',
	'/collections/mozaika-10x10',
	'/collections/mozaika-15x15',
	'/collections/mozaika-20x20',
	'/collections/mozaika-30x30',
	'/collections/mozaika-40x40',
	'/collections/mozaika-30x60',
	'/collections/mozaika-50x50',
	'/collections/mozaika-80x80',
	'/collections/avstraliyskaya-mozaika',
	'/collections/angliyskaya-mozaika',
	'/collections/belorusskaya-mozaika',
	'/collections/bolgarskaya-mozaika',
	'/collections/vetnamskaya-mozaika',
	'/collections/germanskaya-mozaika',
	'/collections/egipetskaya-mozaika',
	'/collections/indiyskaya-mozaika',
	'/collections/ispanskaya-mozaika',
	'/collections/italyanskaya-mozaika',
	'/collections/kitayskaya-mozaika',
	'/collections/litovskaya-mozaika',
	'/collections/moldavskaya-mozaika',
	'/collections/polskaya-mozaika',
	'/collections/portugalskaya-mozaika',
	'/collections/rossiyskaya-mozaika',
	'/collections/tayvanskaya-mozaika',
	'/collections/tunisskaya-mozaika',
	'/collections/turetskaya-mozaika',
	'/collections/ukrainskaya-mozaika',
	'/collections/khorvatskaya-mozaika',
	'/collections/cheshskaya-mozaika',
	'/collections/yuzhno-koreyskaya-mozaika',
	'/collections/glyantsevaya-mozaika',
	'/collections/matovaya-mozaika',
	'/collections/relefnaya-mozaika',
	'/collections/mozaika-iz-kamnya',
	'/collections/obemnaya-mozaika-iz-kamnya',
	'/collections/steklyannaya-mozaika',
	'/collections/mozaika-smes-kamen-steklo',
	'/collections/metallicheskaya-mozaika',
	'/collections/mozaika-iz-rakushek',
	'/collections/morskie-kameshki',
	'/collections/mozaika-dlya-kukhni-na-fartuk',
	'/collections/mozaika-dlya-vannoy',
	'/collections/mozaika-dlya-basseyna',
	'/collections/perlamutrovaya-mozaika',
	'/collections/mozaika-so-strazami-i-kristallami-svarovski',
	'/collections/mozaika-60x60',
	);

if (in_array($_SERVER['SCRIPT_URL'], $genmoz)) {
	define("PAGE_BOTTOM_TEXT", "<p>Мозаика сегодня пользуется большой популярностью, многие профессиональные дизайнеры и обычные потребители выбирают такую плитку для отделки разноплановых интерьеров. Секрет успеха кроется в оригинальной стилистике, превосходных эксплуатационных свойствах и долговечности материала. И для своей коллекции мы отобрали лучшие образцы.</p>
<p>".PAGE_TITLE." — одна из наиболее востребованных категорий товаров. Продукция создана с учетом актуальных модных трендов и строгих стандартов качества. Это универсальные покрытия, не боящиеся механических нагрузок, стойко переносящие смену температурно-влажностного режима и не требующие сложного ухода. Укладывать изделия очень просто благодаря удобному формату и стабильной геометрии, а особая обработка сырья гарантирует надежную защиту от образования грибка и плесени. ".PAGE_TITLE." — отличное решение, если вы хотите получить оригинальный интерьер без баснословных затрат.</p>");
}

$genker= array(
	'/collections/bezhevyy-keramogranit',
	'/collections/belyy-keramogranit',
	'/collections/goluboy-keramogranit',
	'/collections/zheltyy-keramogranit',
	'/collections/zelenyy-keramogranit',
	'/collections/korichnevyy-keramogranit',
	'/collections/krasnyy-keramogranit',
	'/collections/multikolor-keramogranit',
	'/collections/oranzhevyy-keramogranit',
	'/collections/rozovyy-keramogranit',
	'/collections/seryy-keramogranit',
	'/collections/siniy-keramogranit',
	'/collections/fioletovyy-keramogranit',
	'/collections/cherno-belyy-keramogranit',
	'/collections/chernyy-keramogranit',
	'/collections/keramogranit-10x10',
	'/collections/keramogranit-15x15',
	'/collections/keramogranit-20x20',
	'/collections/keramogranit-30x30',
	'/collections/keramogranit-40x40',
	'/collections/keramogranit-50x50',
	'/collections/keramogranit-60x60',
	'/collections/keramogranit-80x80',
	'/collections/keramogranit-30x60',
	'/collections/keramogranit-do-700-rubley',
	'/collections/keramogranit-do-1000-rubley',
	'/collections/keramogranit-do-1500-rubley',
	'/collections/keramogranit-do-2000-rubley',
	'/collections/keramogranit-svyshe-2000-rubley',
	'/collections/glyantsevyy-keramogranit',
	'/collections/matovyy-keramogranit',
	'/collections/relefnyy-keramogranit',
	'/collections/avstraliyskiy-keramogranit',
	'/collections/angliyskiy-keramogranit',
	'/collections/belorusskiy-keramogranit',
	'/collections/bolgarskiy-keramogranit',
	'/collections/vetnamskiy-keramogranit',
	'/collections/germanskiy-keramogranit',
	'/collections/egipetskiy-keramogranit',
	'/collections/indiyskiy-keramogranit',
	'/collections/italyanskiy-keramogranit',
	'/collections/kitayskiy-keramogranit',
	'/collections/litovskiy-keramogranit',
	'/collections/moldavskiy-keramogranit',
	'/collections/polskiy-keramogranit',
	'/collections/portugalskiy-keramogranit',
	'/collections/rossiyskiy-keramogranit',
	'/collections/tayvanskiy-keramogranit',
	'/collections/tunisskiy-keramogranit',
	'/collections/turetskiy-keramogranit',
	'/collections/ukrainskiy-keramogranit',
	'/collections/khorvatskiy-keramogranit',
	'/collections/cheshskiy-keramogranit',
	'/collections/yuzhno-koreyskiy-keramogranit',
	'/collections/keramogranitnye-stupeni',
	'/collections/fasadnaya-plitka-iz-keramogranita',
	);

if (in_array($_SERVER['SCRIPT_URL'], $genker)) {
	define("PAGE_BOTTOM_TEXT", "<p>Керамогранитная плитка выделяется на фоне многочисленных аналогов, представленных на современном рынке отделочных материалов. ".PAGE_TITLE." — яркий представитель данного вида облицовки. Эти покрытия отличаются выдающейся прочностью, что предполагает длительный срок службы без нареканий, высочайшей стойкостью к косметическим и серьезным механическим дефектам (сколам, трещинам), неприхотливостью в уходе, а также абсолютной экологической безопасностью благодаря отборному натуральному сырью.</p>
<p>".PAGE_TITLE." — идеальное решение для помещений с повышенными эксплуатационными нагрузками. Но материал, помимо практических преимуществ, обладает и таким важным достоинством, как эстетичность. Дизайн соответствует самым модным трендам, поэтому о совместимости с интерьером можно не волноваться. В нашей коллекции найдется идеальное решение для любого стиля.</p>");
}

$genklin= array(
	'/collections/klinkernye-stupeni',
	'/collections/fasadnaya-plitka-iz-klinkera',
	'/collections/bezhevye-stupeni',
	'/collections/belye-stupeni',
	'/collections/golubye-stupeni',
	'/collections/zheltye-stupeni',
	'/collections/zelenye-stupeni',
	'/collections/korichnevye-stupeni',
	'/collections/krasnye-stupeni',
	'/collections/multikolor-stupeni',
	'/collections/oranzhevye-stupeni',
	'/collections/rozovye-stupeni',
	'/collections/serye-stupeni',
	'/collections/sinie-stupeni',
	'/collections/fioletovye-stupeni',
	'/collections/cherno-belye-stupeni',
	'/collections/chernye-stupeni',
	'/collections/avstraliyskie-stupeni',
	'/collections/angliyskie-stupeni',
	'/collections/belorusskie-stupeni',
	'/collections/bolgarskie-stupeni',
	'/collections/vetnamskie-stupeni',
	'/collections/germanskie-stupeni',
	'/collections/egipetskie-stupeni',
	'/collections/indiyskie-stupeni',
	'/collections/ispanskie-stupeni',
	'/collections/italyanskie-stupeni',
	'/collections/kitayskie-stupeni',
	'/collections/litovskie-stupeni',
	'/collections/moldavskie-stupeni',
	'/collections/polskie-stupeni',
	'/collections/portugalskie-stupeni',
	'/collections/rossiyskie-stupeni',
	'/collections/tayvanskie-stupeni',
	'/collections/tunisskie-stupeni',
	'/collections/turetskie-stupeni',
	'/collections/ukrainskie-stupeni',
	'/collections/khorvatskie-stupeni',
	'/collections/cheshskie-stupeni',
	'/collections/yuzhno-koreyskie-stupeni',
	'/collections/stupeni-10x10',
	'/collections/stupeni-15x15',
	'/collections/stupeni-20x20',
	'/collections/stupeni-30x30',
	'/collections/stupeni-40x40',
	'/collections/stupeni-50x50',
	'/collections/stupeni-60x60',
	'/collections/stupeni-80x80',
	'/collections/stupeni-30x60',
	'/collections/stupeni-do-700-rubley',
	'/collections/stupeni-do-1000-rubley',
	'/collections/stupeni-do-1500-rubley',
	'/collections/stupeni-do-2000-rubley',
	'/collections/stupeni-svyshe-2000-rubley',
	'/collections/glyantsevye-stupeni',
	'/collections/matovye-stupeni',
	'/collections/relefnye-stupeni',
	'/collections/stupeni-pod-pesok',
	'/collections/stupeni-pod-metall',
	'/collections/stupeni-pod-derevo',
	'/collections/stupeni-pod-kamen',
	'/collections/keramicheskie-stupeni',
	'/collections/monolitnye-stupeni',
	'/collections/protivoskolzyashchie-stupeni',
	'/collections/morozostoykie-stupeni',
	'/collections/keramogranitnye-stupeni',
	'/collections/stupeni-dlya-ulitsy',
	'/collections/stupeni-dlya-kryltsa',
	'/collections/stupeni-dlya-lestnits',	
	);

if (in_array($_SERVER['SCRIPT_URL'], $genklin)) {
	define("PAGE_BOTTOM_TEXT", "<p>Клинкерная плитка и ступени отлично подходят для отделки зон внутри помещений и участков снаружи. Такая универсальность обусловлена безупречными прочностными характеристиками, индифферентностью к агрессии среды (в том числе постоянным перепадам температуры и влажности) и стойкостью к выцветанию и деформированию вследствие механических нагрузок.</p>
<p>".PAGE_TITLE." — одно из лучших решений в данном классе. Изделия создаются из экологически безопасного сырья, которое подвергается особой обработке по инновационной технологии, что гарантирует не только износостойкость, но и прекрасные эстетические качества. Это не просто практичный облицовочный материал, а способ создать уникальную зону комфорта с идеальным балансом функциональности и красоты. ".PAGE_TITLE." — еще и весьма неприхотливая продукция, которой не нужен сложный уход для поддержания презентабельности и продления срока службы.</p>");
}

$genfas= array(
	'/collections/fasadnaya-plitka-iz-keramogranita',
	'/collections/fasadnaya-plitka-iz-klinkera',
	'/collections/fasadnaya-plitka-pod-kirpich',
	'/collections/fasadnaya-plitka-pod-kamen',
	'/collections/fasadnaya-plitka-pod-derevo',
	'/collections/fasadnaya-plitka',
	);

if (in_array($_SERVER['SCRIPT_URL'], $genfas)) {
	define("PAGE_BOTTOM_TEXT", "<p>Фасад любого объекта должен быть долговечным и презентабельным, поэтому часто для облицовки выбирают именно керамическую плитку. Эта разновидность отделочного материала при впечатляющих эксплуатационных характеристиках имеет приемлемую цену, отсюда и высокий спрос. ".PAGE_TITLE." — в списке наиболее популярных образцов. Идеальная проработка фактуры, стильный дизайн, высокая степень износостойкости, простота монтажа и неприхотливость в уходе — вот далеко не полный список достоинств, обусловивших огромные продажи материала.</p>
<p>".PAGE_TITLE." — практичное решение и с точки зрения экологической безопасности. Сырье тщательно проверяется перед поступлением в производство, а потом проходит особую обработку, что в конечном итоге улучшает свойства готовой продукции и продлевает срок ее службы. Новейшие технологии в сочетании с проверенными временем методиками дают возможность создавать не просто плитку, а произведение искусства.</p>");
}
